//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class GVA17
    {
        public int ID_GVA17 { get; set; }
        public string FILLER { get; set; }
        public string COD_ARTICU { get; set; }
        public short NRO_DE_LIS { get; set; }
        public Nullable<decimal> PRECIO { get; set; }
        public Nullable<System.DateTime> FECHA_MODI { get; set; }
        public Nullable<bool> BASE { get; set; }
        public Nullable<System.DateTime> FECHA_PRECIOS_PEDIDOS { get; set; }
    }
}
