//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GASMARKET_TUCUMANEntities : DbContext
    {
        string connectionStringTUC = "data source=VMGASMARKET;initial catalog=GMKT_TUC_2021;user id=consultas;password=consultas;multipleactiveresultsets=True;App=EntityFramework";
        string connectionStringSAL = "data source=gasmarketsalta;initial catalog=GMKT_SALTA_2021;user id=consultas;password=consultas;multipleactiveresultsets=True;App=EntityFramework";
        string connectionStringSGO = "data source=172.19.32.230;initial catalog=GMKT_STGO_2021;user id=consultas;password=consultas;multipleactiveresultsets=True;App=EntityFramework";

        public GASMARKET_TUCUMANEntities(string provincia): base("name=GASMARKET_TUCUMANEntities")
        {
            switch (provincia.ToUpper()) 
            {
                case "TUCUMAN":
                    Database.Connection.ConnectionString = connectionStringTUC;
                    break;
                case "SALTA":
                    Database.Connection.ConnectionString = connectionStringSAL;
                    break;
                case "SANTIAGO DEL ESTERO":
                    Database.Connection.ConnectionString = connectionStringSGO;
                    break;
                default:
                    break;
            }
            
        }


    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<GVA17> GVA17 { get; set; }
    }
}
